import streamlit as st
import os
import time
import shutil
import uuid
from pathlib import Path

# 引入你的核心模块
from src.agent import ResearchAgent
from src.config import (
    DOCS_DIR, RES_DIR, 
    FILE_BASE_INFO, FILE_MEMORY, FILE_FINAL,
    FILE_INNOV_1, FILE_INNOV_2, FILE_INNOV_3
)
from src.prompts import PromptManager

# 引入 Streamlit 官方的回调处理器
from langchain_community.callbacks import StreamlitCallbackHandler

# =============================================================================
# 0. 会话与路径初始化 (Session & Path Init) - [核心修改]
# =============================================================================
# 必须在 set_page_config 之后，其他逻辑之前执行

st.set_page_config(page_title="AI Research Agent", page_icon="🎓", layout="wide")

# 1. 生成唯一会话 ID
if "user_session_id" not in st.session_state:
    # 生成一个随机 UUID 作为当前用户的身份证
    st.session_state.user_session_id = str(uuid.uuid4())

# 2. 定义当前用户的专属资源目录
USER_RES_DIR = RES_DIR / st.session_state.user_session_id

# 3. 确保目录存在
if not USER_RES_DIR.exists():
    USER_RES_DIR.mkdir(parents=True, exist_ok=True)

# 调试信息 (可选，显示在 Sidebar)
# st.sidebar.caption(f"Session: {st.session_state.user_session_id[:8]}")

# =============================================================================
# 1. 辅助工具函数 (Scope 限制在 USER_RES_DIR)
# =============================================================================
def check_milestone(filename):
    """检查当前用户目录下文件是否存在"""
    return (USER_RES_DIR / filename).exists()

def read_file_content(filename):
    """读取当前用户目录下的文件"""
    path = USER_RES_DIR / filename
    if path.exists():
        with open(path, 'r', encoding='utf-8') as f:
            return f.read()
    return None

def clean_project_files(scope="partial"):
    """
    文件清理函数 (仅清理当前用户的文件)
    :param scope: "partial" (仅重置思路) / "full" (彻底重置)
    """
    files_to_remove = [
        FILE_MEMORY, FILE_INNOV_1, FILE_INNOV_2, FILE_INNOV_3, FILE_FINAL, "total.md"
    ]
    
    if scope == "full":
        files_to_remove.append(FILE_BASE_INFO)
        # 清理图片目录
        figures_dir = USER_RES_DIR / "figures"
        if figures_dir.exists():
            try:
                for item in figures_dir.iterdir():
                    if item.is_file(): item.unlink()
            except Exception: pass

    for filename in files_to_remove:
        path = USER_RES_DIR / filename
        if path.exists():
            try:
                os.remove(path)
            except Exception: pass

def merge_final_report():
    """将所有 Markdown 文件合并为 total.md (在用户目录下)"""
    target_files = [FILE_INNOV_1, FILE_INNOV_2, FILE_INNOV_3, FILE_FINAL]
    total_content = ["# Final Integrated Research Proposal\n", "> Auto-generated by AI Research Agent\n", "---\n"]

    for fname in target_files:
        content = read_file_content(fname)
        if content:
            total_content.append(f"\n\n---\n\n") 
            total_content.append(content)

    with open(USER_RES_DIR / "total.md", 'w', encoding='utf-8') as f:
        f.write("".join(total_content))

# =============================================================================
# 2. 状态初始化
# =============================================================================

if "agent" not in st.session_state:
    # [关键修改] 初始化 Agent 时传入 session_id
    st.session_state.agent = ResearchAgent(session_id=st.session_state.user_session_id)

if "messages" not in st.session_state:
    st.session_state.messages = []

# --- 智能状态推断逻辑 (基于用户目录判断) ---
if "phase" not in st.session_state:
    file_phase = "init"
    if check_milestone("total.md"): file_phase = "done" 
    elif check_milestone(FILE_FINAL): file_phase = "final" 
    elif check_milestone(FILE_INNOV_3): file_phase = "final"
    elif check_milestone(FILE_INNOV_2): file_phase = "innov3"
    elif check_milestone(FILE_INNOV_1): file_phase = "innov2"
    elif check_milestone(FILE_BASE_INFO): file_phase = "innov1"
    st.session_state.phase = file_phase

# --- 状态自愈 (State Transition) ---
state_changed = False
if st.session_state.phase == "read" and check_milestone(FILE_BASE_INFO):
    st.session_state.phase = "innov1"
    state_changed = True
elif st.session_state.phase == "innov1" and check_milestone(FILE_INNOV_1):
    st.session_state.phase = "innov2"
    state_changed = True
elif st.session_state.phase == "innov2" and check_milestone(FILE_INNOV_2):
    st.session_state.phase = "innov3"
    state_changed = True
elif st.session_state.phase == "innov3" and check_milestone(FILE_INNOV_3):
    st.session_state.phase = "final" 
    state_changed = True

if state_changed:
    st.rerun()

# =============================================================================
# 3. 模态弹窗
# =============================================================================
@st.dialog("📄 文件预览")
def show_file_content(filename, content):
    # 显示相对路径，不显示长 UUID
    st.caption(f"File: .../{filename}")
    st.markdown(content)

# =============================================================================
# 4. 侧边栏
# =============================================================================
with st.sidebar:
    st.title("🎓 科研助手控制台")
    st.caption(f"Session: {st.session_state.user_session_id[:6]}...")
    
    # [逻辑优化]: 修复上传和选择逻辑
    with st.expander("📂 论文管理", expanded=(st.session_state.phase == "init")):
        uploaded_file = st.file_uploader("上传新论文 (PDF)", type=["pdf"])
        if uploaded_file:
            # 论文还是存在公共 DOCS_DIR，因为原始论文是可以共享的
            # 如果希望论文也隔离，可以将 save_path 改为 USER_RES_DIR
            save_path = DOCS_DIR / uploaded_file.name
            with open(save_path, "wb") as f:
                f.write(uploaded_file.getbuffer())
            
            if "last_processed_file" not in st.session_state or st.session_state.last_processed_file != uploaded_file.name:
                st.session_state.last_processed_file = uploaded_file.name
                st.session_state.pdf_selector = uploaded_file.name
                st.toast(f"已上传并选中: {uploaded_file.name}")

    # 获取文件列表
    pdf_files = list(DOCS_DIR.glob("*.pdf"))
    pdf_names = [f.name for f in pdf_files]

    if "pdf_selector" not in st.session_state:
        st.session_state.pdf_selector = pdf_names[0] if pdf_names else None
    elif st.session_state.pdf_selector not in pdf_names:
        st.session_state.pdf_selector = pdf_names[0] if pdf_names else None

    selected_pdf = st.selectbox(
        "选择目标论文", pdf_names, 
        key="pdf_selector",
        disabled=(st.session_state.phase != "init")
    )
    
    st.divider()
    
    st.subheader("当前进度")
    def render_step_status(label, filename, associated_phases):
        # 使用 unique key 防止组件复用导致的冲突
        step_key = f"step_{filename}_{st.session_state.user_session_id}"
        
        col1, col2 = st.columns([0.8, 0.2])
        is_completed = check_milestone(filename)
        is_doing = (st.session_state.phase in associated_phases) and not is_completed
        
        # 渲染左侧状态文本
        with col1:
            if is_completed: 
                st.markdown(f"✅ ~~{label}~~")
            elif is_doing: 
                st.markdown(f"**🔄 :blue[{label}]**")
            else: 
                st.markdown(f"⚪ <span style='color:grey'>{label}</span>", unsafe_allow_html=True)
        
        # [核心修复] 渲染右侧按钮：无论是否完成，都必须进入 col2 保持 DOM 结构稳定
        with col2:
            if is_completed:
                # 给按钮增加 session_id 后缀，确保全局唯一
                btn_key = f"btn_view_{filename}_{st.session_state.user_session_id}"
                if st.button("📄", key=btn_key, help=f"预览 {filename}"):
                    content = read_file_content(filename)
                    if content: show_file_content(filename, content)
            else:
                # [关键] 即使没有按钮，也要放一个空元素占位
                # 这防止了 "removeChild" 错误，因为节点本身依然存在
                st.empty()

    render_step_status("Base Info Extraction", FILE_BASE_INFO, ["read"])
    render_step_status("Innovation 1", FILE_INNOV_1, ["innov1"])
    render_step_status("Innovation 2", FILE_INNOV_2, ["innov2"])
    render_step_status("Innovation 3", FILE_INNOV_3, ["innov3"])
    render_step_status("Final Experiment", FILE_FINAL, ["final"])
    
    if st.session_state.phase == "done":
         st.markdown("✅ **Total Report Generated**")

    st.divider()
    
    if st.session_state.phase != "done":
        with st.expander("⚠️ 重置选项 (Reset)", expanded=False):
            if st.button("🔙 重置创新点 (Keep Base)"):
                clean_project_files(scope="partial")
                # 保留 session_id 和 agent，只清空消息和状态
                current_id = st.session_state.user_session_id
                st.session_state.clear()
                st.session_state.user_session_id = current_id
                st.rerun()
            if st.button("🆕 彻底重置 (Change Paper)"):
                clean_project_files(scope="full")
                current_id = st.session_state.user_session_id
                st.session_state.clear()
                st.session_state.user_session_id = current_id
                st.rerun()

# =============================================================================
# 5. 主界面逻辑
# =============================================================================

# --- Phase 4: Done (最终展示页) ---
if st.session_state.phase == "done":
    st.header("🏆 最终科研方案 (Final Proposal)")
    
    if not check_milestone("total.md"):
        merge_final_report()
        st.toast("已合并所有文档！")
    
    col1, col2, col3 = st.columns([0.4, 0.3, 0.3])
    
    content = read_file_content("total.md")
    with col1:
        if content:
            st.download_button(
                "📥 下载完整报告 (MD)", content, "total_research.md",
                type="primary", use_container_width=True
            )
            
    with col2:
        if st.button("🔄 保留 Base 重列创新点", help="保留 base.md，删除 innov1/2/3 和 final，重新开始思考创新点。", use_container_width=True):
            clean_project_files(scope="partial")
            current_id = st.session_state.user_session_id
            st.session_state.clear()
            st.session_state.user_session_id = current_id
            st.rerun()
            
    with col3:
        if st.button("🚀 开启新论文 (Full Reset)", help="删除所有文件，回到初始状态。", use_container_width=True):
            clean_project_files(scope="full")
            current_id = st.session_state.user_session_id
            st.session_state.clear()
            st.session_state.user_session_id = current_id
            st.rerun()
            
    st.divider()
    
    if content:
        st.markdown(content)
    else:
        st.error("Error: total.md 生成失败。")
        
    st.stop() 

# --- 以下是交互阶段 (Init -> Final) ---

st.header("AI Research Agent: Top-Tier Paper Innovation")

# 渲染历史消息
for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.markdown(message["content"])

# --- Phase 0: Init ---
if st.session_state.phase == "init":
    if not selected_pdf:
        st.info("👈 请在左侧侧边栏上传 PDF 论文。")
    else:
        st.info(f"就绪。目标论文：**{selected_pdf}**")
        if st.button("开始阅读论文", type="primary"):
            st.session_state.phase = "read"
            # 初始化记忆文件到用户目录
            if not (USER_RES_DIR / FILE_MEMORY).exists():
                with open(USER_RES_DIR / FILE_MEMORY, 'w', encoding='utf-8') as f:
                    f.write(PromptManager.get_memory_init_content())
            st.rerun()

# --- Phase 1: Read ---
elif st.session_state.phase == "read":
    if not check_milestone(FILE_BASE_INFO):
        st.session_state.agent.update_phase("read")
        trigger_msg = f"请读取文件 '{selected_pdf}'，分析其核心方法和理论，并建立 '{FILE_BASE_INFO}'。"
        
        if not st.session_state.messages or st.session_state.messages[-1]["content"] != trigger_msg:
            st.session_state.messages.append({"role": "user", "content": trigger_msg})
            st.rerun()
        
        if st.session_state.messages[-1]["role"] == "user":
            with st.chat_message("assistant"):
                st_callback = StreamlitCallbackHandler(st.container())
                response_placeholder = st.empty()
                full_response = ""
                try:
                    stream = st.session_state.agent.chat_stream(trigger_msg, callbacks=[st_callback])
                    for chunk in stream:
                        full_response += chunk
                        response_placeholder.markdown(full_response + "▌")
                    response_placeholder.markdown(full_response)
                    st.session_state.messages.append({"role": "assistant", "content": full_response})
                    
                    st.rerun()
                except Exception as e:
                    st.error(f"Execution Error: {str(e)}")
    else:
        st.session_state.phase = "innov1"
        st.rerun()

# --- Phase 2: Innovations (1, 2, 3) ---
elif st.session_state.phase in ["innov1", "innov2", "innov3"]:
    phase_map = {"innov1": (FILE_INNOV_1, 1), "innov2": (FILE_INNOV_2, 2), "innov3": (FILE_INNOV_3, 3)}
    current_file, stage_num = phase_map[st.session_state.phase]

    if f"ready_{st.session_state.phase}" not in st.session_state:
        context = {
            "base_summary": read_file_content(FILE_BASE_INFO),
            "memory_log": read_file_content(FILE_MEMORY)
        }
        st.session_state.agent.update_phase(st.session_state.phase, context)
        st.session_state.agent.clear_short_term_memory()
        
        welcome_msg = f"**[Phase 2-{stage_num}]** 已就绪。请提出关于 **创新点 {stage_num}** 的思路。"
        st.session_state.messages.append({"role": "assistant", "content": welcome_msg})
        st.session_state[f"ready_{st.session_state.phase}"] = True
        st.rerun()

    if prompt := st.chat_input(f"描述创新点 {stage_num} 思路..."):
        st.session_state.messages.append({"role": "user", "content": prompt})
        with st.chat_message("user"):
            st.markdown(prompt)

        with st.chat_message("assistant"):
            st_callback = StreamlitCallbackHandler(st.container())
            response_placeholder = st.empty()
            full_response = ""
            
            try:
                stream_generator = st.session_state.agent.chat_stream(prompt, callbacks=[st_callback])
                for chunk in stream_generator:
                    full_response += chunk
                    response_placeholder.markdown(full_response + "▌")
                response_placeholder.markdown(full_response)
                
                st.session_state.messages.append({"role": "assistant", "content": full_response})

                if check_milestone(current_file):
                    st.success(f"🎉 创新点 {stage_num} 已归档！")
                    time.sleep(1)
                    st.rerun()
            except Exception as e:
                st.error(f"Error: {e}")

# --- Phase 3: Final Experiment ---
elif st.session_state.phase == "final":
    
    if not check_milestone(FILE_FINAL):
        if "final_triggered" not in st.session_state:
            context = {"base_summary": read_file_content(FILE_BASE_INFO)}
            st.session_state.agent.update_phase("final", context)
            st.session_state.agent.clear_short_term_memory()
            
            trigger = "三个创新点已就绪。请读取所有 innov 文件，设计最终的对比实验和消融实验方案，并写入 final_innov.md。"
            st.session_state.messages.append({"role": "user", "content": trigger})
            st.session_state["final_triggered"] = True
            st.rerun() 

        if st.session_state.messages[-1]["role"] == "user":
            with st.chat_message("assistant"):
                st_callback = StreamlitCallbackHandler(st.container())
                response_placeholder = st.empty()
                full_response = ""
                
                try:
                    trigger = st.session_state.messages[-1]["content"]
                    stream = st.session_state.agent.chat_stream(trigger, callbacks=[st_callback])
                    for chunk in stream:
                        full_response += chunk
                        response_placeholder.markdown(full_response + "▌")
                    response_placeholder.markdown(full_response)
                    
                    st.session_state.messages.append({"role": "assistant", "content": full_response})
                    
                    if check_milestone(FILE_FINAL):
                        st.rerun() 
                except Exception as e:
                    st.error(f"Execution Error: {str(e)}")
                    del st.session_state["final_triggered"]

    else:
        st.success("✅ 最终实验方案 (final_innov.md) 已设计完成！")
        st.info("Agent 已综合所有创新点并设计了实验。")
        
        if st.button("🏁 生成最终汇总报告 (Merge & Finish)", type="primary"):
            merge_final_report() 
            st.session_state.phase = "done"
            st.rerun()